### ISSUE TITLE
Corrupted double-linked list after finishing 3rd mission 

### ISSUE THREAD

**Issue by Szunti** [Andrettin/Wyrmgus#10]
Git master of Wyrmgus and Wyrmsun. Just when I clicked on continue in the message window that popups when killing the last enemy unit.

Stderr:
```
*** Error in `./stratagus': corrupted double-linked list: 0x00000000048ff130 ***
```

It was an optimized build without debug symbols, so I don't know how good will be the backtrace:
I leave it open, so you can ask for additional info if you want.

Backtrace:
```
#0  0x00007fc45d7530eb in __lll_lock_wait_private ()
   from /usr/lib/libc.so.6
#1  0x00007fc45d6d98ac in malloc () from /usr/lib/libc.so.6
#2  0x00007fc46065a25b in _dl_map_object_deps ()
   from /lib64/ld-linux-x86-64.so.2
#3  0x00007fc460660358 in dl_open_worker ()
   from /lib64/ld-linux-x86-64.so.2
#4  0x00007fc46065bf94 in _dl_catch_error ()
   from /lib64/ld-linux-x86-64.so.2
#5  0x00007fc46065fe01 in _dl_open () from /lib64/ld-linux-x86-64.so.2
#6  0x00007fc45d77b84d in do_dlopen () from /usr/lib/libc.so.6
#7  0x00007fc46065bf94 in _dl_catch_error ()
   from /lib64/ld-linux-x86-64.so.2
#8  0x00007fc45d77b8df in dlerror_run () from /usr/lib/libc.so.6
#9  0x00007fc45d77b951 in __libc_dlopen_mode () from /usr/lib/libc.so.6
#10 0x00007fc45d753965 in init () from /usr/lib/libc.so.6
#11 0x00007fc45fb2bdcf in __pthread_once_slow ()
   from /usr/lib/libpthread.so.0
#12 0x00007fc45d753a7c in backtrace () from /usr/lib/libc.so.6
#13 0x00007fc45d67eb02 in backtrace_and_maps () from /usr/lib/libc.so.6
#14 0x00007fc45d6d0bad in __libc_message () from /usr/lib/libc.so.6
#15 0x00007fc45d6d60fe in malloc_printerr () from /usr/lib/libc.so.6
#16 0x00007fc45d6d70b9 in _int_free () from /usr/lib/libc.so.6
#17 0x000000000058fc4a in CUnit::Release(bool) ()
#18 0x000000000059448d in CleanUnits() ()
#19 0x00000000004a4c1f in StartMap(std::string const&, bool) ()
#20 0x00000000006091ef in tolua_stratagus_StartMap00(lua_State*) ()
#21 0x00007fc46042c1e8 in ?? () from /usr/lib/liblua5.1.so.5.1
#22 0x00007fc46043692f in ?? () from /usr/lib/liblua5.1.so.5.1
#23 0x00007fc46042c62d in ?? () from /usr/lib/liblua5.1.so.5.1
#24 0x00007fc46042b91b in ?? () from /usr/lib/liblua5.1.so.5.1
#25 0x00007fc46042c7ba in ?? () from /usr/lib/liblua5.1.so.5.1
#26 0x00007fc46042857d in lua_pcall () from /usr/lib/liblua5.1.so.5.1
#27 0x0000000000520b6b in LuaCallback::run(int) ()
#28 0x000000000056dba1 in LuaActionListener::action(std::string const&)
    ()
#29 0x00000000004b61bd in gcn::Widget::generateAction() ()
#30 0x00000000004b547e in gcn::Widget::_mouseInputMessage(gcn::MouseInput const&) ()
#31 0x00000000004b7bea in gcn::Container::_mouseInputMessage(gcn::MouseInput const&) ()
#32 0x00000000004af1b2 in gcn::Gui::logic() ()
#33 0x00000000005c908b in WaitEventsOneFrame() ()
#34 0x000000000057224e in MenuScreen::run(bool) ()
#35 0x00000000005fbe58 in tolua_stratagus_CMenuScreen_run00(lua_State*)
    ()
#36 0x00007fc46042c1e8 in ?? () from /usr/lib/liblua5.1.so.5.1
#37 0x00007fc46043692f in ?? () from /usr/lib/liblua5.1.so.5.1
---Type <return> to continue, or q <return> to quit---
#38 0x00007fc46042c62d in ?? () from /usr/lib/liblua5.1.so.5.1
#39 0x00007fc46042b91b in ?? () from /usr/lib/liblua5.1.so.5.1
#40 0x00007fc46042c7ba in ?? () from /usr/lib/liblua5.1.so.5.1
#41 0x00007fc46042857d in lua_pcall () from /usr/lib/liblua5.1.so.5.1
#42 0x0000000000520b6b in LuaCallback::run(int) ()
#43 0x000000000056dba1 in LuaActionListener::action(std::string const&)
    ()
#44 0x00000000004b61bd in gcn::Widget::generateAction() ()
#45 0x00000000004b547e in gcn::Widget::_mouseInputMessage(gcn::MouseInput const&) ()
#46 0x00000000004b7bea in gcn::Container::_mouseInputMessage(gcn::MouseInput const&) ()
#47 0x00000000004af1b2 in gcn::Gui::logic() ()
#48 0x00000000005c908b in WaitEventsOneFrame() ()
#49 0x000000000057224e in MenuScreen::run(bool) ()
#50 0x00000000005fbe58 in tolua_stratagus_CMenuScreen_run00(lua_State*)
    ()
#51 0x00007fc46042c1e8 in ?? () from /usr/lib/liblua5.1.so.5.1
#52 0x00007fc46043692f in ?? () from /usr/lib/liblua5.1.so.5.1
#53 0x00007fc46042c62d in ?? () from /usr/lib/liblua5.1.so.5.1
#54 0x00007fc46042b91b in ?? () from /usr/lib/liblua5.1.so.5.1
#55 0x00007fc46042c7ba in ?? () from /usr/lib/liblua5.1.so.5.1
#56 0x00007fc46042857d in lua_pcall () from /usr/lib/liblua5.1.so.5.1
#57 0x0000000000520b6b in LuaCallback::run(int) ()
#58 0x000000000056dba1 in LuaActionListener::action(std::string const&)
    ()
#59 0x00000000004b61bd in gcn::Widget::generateAction() ()
#60 0x00000000004b547e in gcn::Widget::_mouseInputMessage(gcn::MouseInput const&) ()
#61 0x00000000004b7bea in gcn::Container::_mouseInputMessage(gcn::MouseInput const&) ()
#62 0x00000000004af1b2 in gcn::Gui::logic() ()
#63 0x00000000005c908b in WaitEventsOneFrame() ()
#64 0x000000000057224e in MenuScreen::run(bool) ()
#65 0x00000000005fbe58 in tolua_stratagus_CMenuScreen_run00(lua_State*)
    ()
#66 0x00007fc46042c1e8 in ?? () from /usr/lib/liblua5.1.so.5.1
#67 0x00007fc46043692f in ?? () from /usr/lib/liblua5.1.so.5.1
#68 0x00007fc46042c62d in ?? () from /usr/lib/liblua5.1.so.5.1
#69 0x00007fc46042b91b in ?? () from /usr/lib/liblua5.1.so.5.1
#70 0x00007fc46042c7ba in ?? () from /usr/lib/liblua5.1.so.5.1
#71 0x00007fc46042857d in lua_pcall () from /usr/lib/liblua5.1.so.5.1
#72 0x0000000000520b6b in LuaCallback::run(int) ()
#73 0x000000000056dba1 in LuaActionListener::action(std::string const&)
    ()
#74 0x00000000004b61bd in gcn::Widget::generateAction() ()
#75 0x00000000004b547e in gcn::Widget::_mouseInputMessage(gcn::MouseInput const&) ()
---Type <return> to continue, or q <return> to quit---
#76 0x00000000004b7bea in gcn::Container::_mouseInputMessage(gcn::MouseInput const&) ()
#77 0x00000000004af1b2 in gcn::Gui::logic() ()
#78 0x00000000005c908b in WaitEventsOneFrame() ()
#79 0x000000000057224e in MenuScreen::run(bool) ()
#80 0x00000000005fbe58 in tolua_stratagus_CMenuScreen_run00(lua_State*)
    ()
#81 0x00007fc46042c1e8 in ?? () from /usr/lib/liblua5.1.so.5.1
#82 0x00007fc46043692f in ?? () from /usr/lib/liblua5.1.so.5.1
#83 0x00007fc46042c62d in ?? () from /usr/lib/liblua5.1.so.5.1
#84 0x00007fc46042b91b in ?? () from /usr/lib/liblua5.1.so.5.1
#85 0x00007fc46042c7ba in ?? () from /usr/lib/liblua5.1.so.5.1
#86 0x00007fc46042857d in lua_pcall () from /usr/lib/liblua5.1.so.5.1
#87 0x0000000000520b6b in LuaCallback::run(int) ()
#88 0x000000000056dba1 in LuaActionListener::action(std::string const&)
    ()
#89 0x00000000004b61bd in gcn::Widget::generateAction() ()
#90 0x00000000004b547e in gcn::Widget::_mouseInputMessage(gcn::MouseInput const&) ()
#91 0x00000000004b7bea in gcn::Container::_mouseInputMessage(gcn::MouseInput const&) ()
#92 0x00000000004af1b2 in gcn::Gui::logic() ()
#93 0x00000000005c908b in WaitEventsOneFrame() ()
#94 0x000000000057224e in MenuScreen::run(bool) ()
#95 0x00000000005fbe58 in tolua_stratagus_CMenuScreen_run00(lua_State*)
    ()
#96 0x00007fc46042c1e8 in ?? () from /usr/lib/liblua5.1.so.5.1
#97 0x00007fc460436899 in ?? () from /usr/lib/liblua5.1.so.5.1
#98 0x00007fc46042c62d in ?? () from /usr/lib/liblua5.1.so.5.1
#99 0x00007fc46042b91b in ?? () from /usr/lib/liblua5.1.so.5.1
#100 0x00007fc46042c7ba in ?? () from /usr/lib/liblua5.1.so.5.1
#101 0x00007fc46042857d in lua_pcall () from /usr/lib/liblua5.1.so.5.1
#102 0x0000000000520b6b in LuaCallback::run(int) ()
#103 0x000000000056dba1 in LuaActionListener::action(std::string const&)
    ()
#104 0x00000000004b61bd in gcn::Widget::generateAction() ()
#105 0x00000000004b547e in gcn::Widget::_mouseInputMessage(gcn::MouseInput const&) ()
#106 0x00000000004b7bea in gcn::Container::_mouseInputMessage(gcn::MouseInput const&) ()
#107 0x00000000004af1b2 in gcn::Gui::logic() ()
#108 0x00000000005c908b in WaitEventsOneFrame() ()
#109 0x000000000057224e in MenuScreen::run(bool) ()
#110 0x00000000005fbe58 in tolua_stratagus_CMenuScreen_run00(lua_State*)
    ()
#111 0x00007fc46042c1e8 in ?? () from /usr/lib/liblua5.1.so.5.1
#112 0x00007fc460436899 in ?? () from /usr/lib/liblua5.1.so.5.1
#113 0x00007fc46042c62d in ?? () from /usr/lib/liblua5.1.so.5.1
---Type <return> to continue, or q <return> to quit---
#114 0x00007fc46042b91b in ?? () from /usr/lib/liblua5.1.so.5.1
#115 0x00007fc46042c7ba in ?? () from /usr/lib/liblua5.1.so.5.1
#116 0x00007fc46042857d in lua_pcall () from /usr/lib/liblua5.1.so.5.1
#117 0x0000000000520b6b in LuaCallback::run(int) ()
#118 0x000000000056dba1 in LuaActionListener::action(std::string const&)
    ()
#119 0x00000000004b61bd in gcn::Widget::generateAction() ()
#120 0x00000000004b547e in gcn::Widget::_mouseInputMessage(gcn::MouseInput const&) ()
#121 0x00000000004b7bea in gcn::Container::_mouseInputMessage(gcn::MouseInput const&) ()
#122 0x00000000004af1b2 in gcn::Gui::logic() ()
#123 0x00000000005c908b in WaitEventsOneFrame() ()
#124 0x000000000057224e in MenuScreen::run(bool) ()
#125 0x00000000005fbe58 in tolua_stratagus_CMenuScreen_run00(lua_State*)
    ()
#126 0x00007fc46042c1e8 in ?? () from /usr/lib/liblua5.1.so.5.1
#127 0x00007fc460436899 in ?? () from /usr/lib/liblua5.1.so.5.1
#128 0x00007fc46042c62d in ?? () from /usr/lib/liblua5.1.so.5.1
#129 0x00007fc46042b91b in ?? () from /usr/lib/liblua5.1.so.5.1
#130 0x00007fc46042c7ba in ?? () from /usr/lib/liblua5.1.so.5.1
#131 0x00007fc46042857d in lua_pcall () from /usr/lib/liblua5.1.so.5.1
#132 0x0000000000529dac in LuaCall(int, int, bool) ()
#133 0x000000000052ce1c in LuaLoadFile(std::string const&) ()
#134 0x000000000053e82d in stratagusMain(int, char**) ()
#135 0x00007fc45d67f790 in __libc_start_main () from /usr/lib/libc.so.6
#136 0x000000000045a649 in _start ()
```

**Comment by Andrettin** [comment]
Thanks for the report! This was with the Northwards to the Sea mission, right? The only thing that happens with that trigger (besides saving the completed quest in your preferences if it's the first time you complete it) is to make the player win.

It seems like an error happened when the game was cleansed of a particular unit after the scenario ended, but I haven't quite yet got an idea of what the issue could be more precisely.

**Comment by Szunti** [comment]
Yes, should be that mission.
