### ISSUE TITLE
Crash with right click

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#100]
Wyrmgus & Wyrmsun the latest, as usual.

Here is the situation when I had this segfault:
![2016-07-21 16-44-24](https://cloud.githubusercontent.com/assets/1813101/17024995/01e86c8e-4f6b-11e6-9b56-8782249a31aa.png)

I pressed on the tower to repair it. Backtrace:

```
Thread 1 "stratagus-dbg" received signal SIGSEGV, Segmentation fault.
malloc_consolidate (av=av@entry=0x7ffff5e24b20 <main_arena>) at malloc.c:4182
4182    malloc.c: No such file or directory.
(gdb) bt
#0  malloc_consolidate (av=av@entry=0x7ffff5e24b20 <main_arena>)
    at malloc.c:4182
#1  0x00007ffff5ae255e in _int_malloc (
    av=av@entry=0x7ffff5e24b20 <main_arena>, bytes=bytes@entry=2984)
    at malloc.c:3451
#2  0x00007ffff5ae45a4 in __GI___libc_malloc (bytes=2984) at malloc.c:2914
#3  0x00007ffff63d6e78 in operator new(unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00000000006a8490 in __gnu_cxx::new_allocator<CUnit*>::allocate (
    this=0x7fffffffc0f0, __n=373) at /usr/include/c++/5/ext/new_allocator.h:104
#5  0x00000000006a8149 in std::allocator_traits<std::allocator<CUnit*> >::allocate (__a=..., __n=373) at /usr/include/c++/5/bits/alloc_traits.h:491
#6  0x00000000006a7bf0 in std::_Vector_base<CUnit*, std::allocator<CUnit*> >::_M_allocate (this=0x7fffffffc0f0, __n=373)
    at /usr/include/c++/5/bits/stl_vector.h:170
#7  0x00000000006ca474 in std::vector<CUnit*, std::allocator<CUnit*> >::_M_range_initialize<__gnu_cxx::__normal_iterator<CUnit**, std::vector<CUnit*, std::allocator<CUnit*> > > > (this=0x7fffffffc0f0, __first=, __last=)
    at /usr/include/c++/5/bits/stl_vector.h:1287
#8  0x00000000006c9eee in std::vector<CUnit*, std::allocator<CUnit*> >::_M_initialize_dispatch<__gnu_cxx::__normal_iterator<CUnit**, std::vector<CUnit*, std::allocator<CUnit*> > > > (this=0x7fffffffc0f0, __first=, __last=)
    at /usr/include/c++/5/bits/stl_vector.h:1263
---Type <return> to continue, or q <return> to quit---
#9  0x00000000006c9bcb in std::vector<CUnit*, std::allocator<CUnit*> >::vector<__gnu_cxx::__normal_iterator<CUnit**, std::vector<CUnit*, std::allocator<CUnit*> > >, void> (this=0x7fffffffc0f0, __first=, __last=, __a=...)
    at /usr/include/c++/5/bits/stl_vector.h:404
#10 0x00000000006c9378 in UnitActions ()
    at /home/kroartem/SVN/Wyrmgus/src/action/actions.cpp:619
#11 0x0000000000856674 in GameLogicLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:487
#12 0x0000000000856d5a in SingleGameLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:670
#13 0x000000000085704a in GameMainLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:729
#14 0x000000000071797d in StartMap (
    filename="maps/random/random-map-valley.smp", clean=true)
    at /home/kroartem/SVN/Wyrmgus/src/game/game.cpp:193
#15 0x0000000000a21806 in tolua_stratagus_StartMap00 (tolua_S=0x1ae2bf0)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:1075
#16 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#17 0x00007ffff7bbfeea in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#18 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#19 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#20 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#21 0x00007ffff7bb13a8 in lua_pcall ()
---Type <return> to continue, or q <return> to quit---
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#22 0x0000000000852597 in LuaCallback::run (this=0x177a1518, results=0)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/luacallback.cpp:149
#23 0x000000000095028a in LuaActionListener::action (this=0x177a1510, 
    eventId="") at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:494
#24 0x000000000073cb2e in gcn::Widget::generateAction (this=0x177a12d0)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:616
#25 0x000000000074018f in gcn::Button::mouseClick (this=0x177a12d0, button=1)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/button.cpp:254
#26 0x000000000073c567 in gcn::Widget::_mouseInputMessage (this=0x177a12d0, 
    mouseInput=...) at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:502
#27 0x0000000000741e63 in gcn::Container::_mouseInputMessage (this=0x17756f60, 
    mouseInput=...)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/container.cpp:394
#28 0x0000000000733ee0 in gcn::Gui::logic (this=0x170be910)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/gui.cpp:155
#29 0x00000000009500b9 in handleInput (event=0x0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:443
#30 0x0000000000a08efe in WaitEventsOneFrame ()
    at /home/kroartem/SVN/Wyrmgus/src/video/sdl.cpp:977
#31 0x000000000095c0a9 in MenuScreen::run (this=0x17756f60, loop=true)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:3182
#32 0x0000000000a6e2a7 in tolua_stratagus_CMenuScreen_run00 (tolua_S=0x1ae2bf0)
---Type <return> to continue, or q <return> to quit---
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:27288
#33 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#34 0x00007ffff7bbfeea in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#35 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#36 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#37 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#38 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#39 0x0000000000852597 in LuaCallback::run (this=0x1754e8f8, results=0)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/luacallback.cpp:149
#40 0x000000000095028a in LuaActionListener::action (this=0x1754e8f0, 
    eventId="") at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:494
#41 0x000000000073cb2e in gcn::Widget::generateAction (this=0x175ee550)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:616
#42 0x000000000074018f in gcn::Button::mouseClick (this=0x175ee550, button=1)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/button.cpp:254
#43 0x000000000073c567 in gcn::Widget::_mouseInputMessage (this=0x175ee550, 
    mouseInput=...) at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:502
#44 0x0000000000741e63 in gcn::Container::_mouseInputMessage (this=0x175ee8b0, 
    mouseInput=...)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/container.cpp:394
#45 0x0000000000733ee0 in gcn::Gui::logic (this=0x170be910)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/gui.cpp:155
---Type <return> to continue, or q <return> to quit---
#46 0x00000000009500b9 in handleInput (event=0x0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:443
#47 0x0000000000a08efe in WaitEventsOneFrame ()
    at /home/kroartem/SVN/Wyrmgus/src/video/sdl.cpp:977
#48 0x000000000095c0a9 in MenuScreen::run (this=0x175ee8b0, loop=true)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:3182
#49 0x0000000000a6e2a7 in tolua_stratagus_CMenuScreen_run00 (tolua_S=0x1ae2bf0)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:27288
#50 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#51 0x00007ffff7bbfe87 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#52 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#53 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#54 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#55 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#56 0x0000000000852597 in LuaCallback::run (this=0x171cac48, results=0)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/luacallback.cpp:149
#57 0x000000000095028a in LuaActionListener::action (this=0x171cac40, 
    eventId="") at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:494
#58 0x000000000073cb2e in gcn::Widget::generateAction (this=0x171caa80)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:616
#59 0x000000000074018f in gcn::Button::mouseClick (this=0x171caa80, button=1)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/button.cpp:254
---Type <return> to continue, or q <return> to quit---
#60 0x000000000073c567 in gcn::Widget::_mouseInputMessage (this=0x171caa80, 
    mouseInput=...) at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:502
#61 0x0000000000741e63 in gcn::Container::_mouseInputMessage (this=0x17128140, 
    mouseInput=...)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/container.cpp:394
#62 0x0000000000733ee0 in gcn::Gui::logic (this=0x170be910)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/gui.cpp:155
#63 0x00000000009500b9 in handleInput (event=0x0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:443
#64 0x0000000000a08efe in WaitEventsOneFrame ()
    at /home/kroartem/SVN/Wyrmgus/src/video/sdl.cpp:977
#65 0x000000000095c0a9 in MenuScreen::run (this=0x17128140, loop=true)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:3182
#66 0x0000000000a6e2a7 in tolua_stratagus_CMenuScreen_run00 (tolua_S=0x1ae2bf0)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:27288
#67 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#68 0x00007ffff7bbfe87 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#69 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#70 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#71 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#72 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#73 0x000000000087ed05 in LuaCall (narg=0, clear=1, exitOnError=true)
---Type <return> to continue, or q <return> to quit---
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script.cpp:185
#74 0x000000000087f096 in LuaLoadFile (file="scripts/guichan.lua", strArg="")
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script.cpp:246
#75 0x00000000008ee78b in MenuLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/stratagus.cpp:313
#76 0x00000000008ef258 in stratagusMain (argc=1, argv=0x7fffffffdbd8)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/stratagus.cpp:822
#77 0x0000000000854bf4 in main (argc=1, argv=0x7fffffffdbd8)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/main.cpp:37
```

**Comment by Andrettin** [comment]
Thanks for the report! Unfortunately it is a bit hard to tell what the problem is just by looking at this output. Was it a saved game?

**Comment by KroArtem** [comment]
No, I didn't have any savegame before this moment.

**Comment by KroArtem** [comment]
Closing this issue as of https://github.com/Andrettin/Wyrmsun/issues/21#issuecomment-504457419
