### ISSUE TITLE
One more crash

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#102]
Not very helpful title and I don't have any ideas. Right now will leave it here.

```
Thread 1 "stratagus-dbg" received signal SIGSEGV, Segmentation fault.
0x0000000000701aa8 in std::vector<COrder*, std::allocator<COrder*> >::operator[] (this=0x4b8a, __n=0) at /usr/include/c++/5/bits/stl_vector.h:795
795       { return *(this->_M_impl._M_start + __n); }
(gdb) bt
#0  0x0000000000701aa8 in std::vector<COrder*, std::allocator<COrder*> >::operator[] (this=0x4b8a, __n=0) at /usr/include/c++/5/bits/stl_vector.h:795
#1  0x000000000070176b in CUnit::CurrentOrder (this=0x82)
    at /home/kroartem/SVN/Wyrmgus/src/include/unit.h:135
#2  0x0000000000a3c530 in CUnit::CurrentAction (this=0x82)
    at /home/kroartem/SVN/Wyrmgus/src/unit/unit.cpp:1892
#3  0x00000000008eb217 in CPlayer::GetUnitTotalCount (
    this=0x2093910 <Players+60528>, type=...)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/player.cpp:2097
#4  0x00000000008eb4a3 in CPlayer::CheckLimits (
    this=0x2093910 <Players+60528>, type=...)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/player.cpp:2138
#5  0x0000000000754f58 in AiCheckingWork ()
    at /home/kroartem/SVN/Wyrmgus/src/ai/ai_resource.cpp:886
#6  0x0000000000757568 in AiResourceManager ()
    at /home/kroartem/SVN/Wyrmgus/src/ai/ai_resource.cpp:1660
#7  0x0000000000745144 in AiEachSecond (player=...)
    at /home/kroartem/SVN/Wyrmgus/src/ai/ai.cpp:1147
#8  0x00000000008ebd2f in PlayersEachSecond (playerIdx=1)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/player.cpp:2364
#9  0x00000000008e0a1e in GameLogicLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:548
#10 0x00000000008e0fe6 in SingleGameLoop ()
---Type <return> to continue, or q <return> to quit---
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:701
#11 0x00000000008e12d6 in GameMainLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:760
#12 0x000000000077cbbf in StartMap (
    filename="maps/random/random-map-swamp.smp", clean=true)
    at /home/kroartem/SVN/Wyrmgus/src/game/game.cpp:196
#13 0x0000000000ab9200 in tolua_stratagus_StartMap00 (tolua_S=0x21a4bf0)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:1075
#14 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#15 0x00007ffff7bbfeea in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#16 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#17 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#18 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#19 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#20 0x00000000008dc439 in LuaCallback::run (this=0x19104708, results=0)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/luacallback.cpp:149
#21 0x00000000009e757c in LuaActionListener::action (this=0x19104700, 
    eventId="") at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:494
#22 0x00000000007a55c0 in gcn::Widget::generateAction (this=0x191044c0)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:616
#23 0x00000000007a8c21 in gcn::Button::mouseClick (this=0x191044c0, button=1)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/button.cpp:254
---Type <return> to continue, or q <return> to quit---
#24 0x00000000007a4ff9 in gcn::Widget::_mouseInputMessage (this=0x191044c0, 
    mouseInput=...) at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:502
#25 0x00000000007aa8f5 in gcn::Container::_mouseInputMessage (this=0x190ee320, 
    mouseInput=...)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/container.cpp:394
#26 0x000000000079c972 in gcn::Gui::logic (this=0x19097ec0)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/gui.cpp:155
#27 0x00000000009e73ab in handleInput (event=0x0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:443
#28 0x0000000000aa0a94 in WaitEventsOneFrame ()
    at /home/kroartem/SVN/Wyrmgus/src/video/sdl.cpp:977
#29 0x00000000009f339b in MenuScreen::run (this=0x190ee320, loop=true)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:3182
#30 0x0000000000b06980 in tolua_stratagus_CMenuScreen_run00 (tolua_S=0x21a4bf0)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:27480
#31 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#32 0x00007ffff7bbfeea in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#33 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#34 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#35 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#36 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#37 0x00000000008dc439 in LuaCallback::run (this=0x193a4a68, results=0)
---Type <return> to continue, or q <return> to quit---
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/luacallback.cpp:149
#38 0x00000000009e757c in LuaActionListener::action (this=0x193a4a60, 
    eventId="") at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:494
#39 0x00000000007a55c0 in gcn::Widget::generateAction (this=0x190d2180)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:616
#40 0x00000000007a8c21 in gcn::Button::mouseClick (this=0x190d2180, button=1)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/button.cpp:254
#41 0x00000000007a4ff9 in gcn::Widget::_mouseInputMessage (this=0x190d2180, 
    mouseInput=...) at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:502
#42 0x00000000007aa8f5 in gcn::Container::_mouseInputMessage (this=0x19178130, 
    mouseInput=...)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/container.cpp:394
#43 0x000000000079c972 in gcn::Gui::logic (this=0x19097ec0)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/gui.cpp:155
#44 0x00000000009e73ab in handleInput (event=0x0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:443
#45 0x0000000000aa0a94 in WaitEventsOneFrame ()
    at /home/kroartem/SVN/Wyrmgus/src/video/sdl.cpp:977
#46 0x00000000009f339b in MenuScreen::run (this=0x19178130, loop=true)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:3182
#47 0x0000000000b06980 in tolua_stratagus_CMenuScreen_run00 (tolua_S=0x21a4bf0)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:27480
#48 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
---Type <return> to continue, or q <return> to quit---
#49 0x00007ffff7bbfe87 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#50 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#51 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#52 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#53 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#54 0x00000000008dc439 in LuaCallback::run (this=0x98d68c8, results=0)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/luacallback.cpp:149
#55 0x00000000009e757c in LuaActionListener::action (this=0x98d68c0, 
    eventId="") at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:494
#56 0x00000000007a55c0 in gcn::Widget::generateAction (this=0x19418280)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:616
#57 0x00000000007a8c21 in gcn::Button::mouseClick (this=0x19418280, button=1)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/button.cpp:254
#58 0x00000000007a4ff9 in gcn::Widget::_mouseInputMessage (this=0x19418280, 
    mouseInput=...) at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:502
#59 0x00000000007aa8f5 in gcn::Container::_mouseInputMessage (this=0x1935f970, 
    mouseInput=...)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/container.cpp:394
#60 0x000000000079c972 in gcn::Gui::logic (this=0x19097ec0)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/gui.cpp:155
#61 0x00000000009e73ab in handleInput (event=0x0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:443
---Type <return> to continue, or q <return> to quit---
#62 0x0000000000aa0a94 in WaitEventsOneFrame ()
    at /home/kroartem/SVN/Wyrmgus/src/video/sdl.cpp:977
#63 0x00000000009f339b in MenuScreen::run (this=0x1935f970, loop=true)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:3182
#64 0x0000000000b06980 in tolua_stratagus_CMenuScreen_run00 (tolua_S=0x21a4bf0)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:27480
#65 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#66 0x00007ffff7bbfe87 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#67 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#68 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#69 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#70 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#71 0x0000000000912f81 in LuaCall (narg=0, clear=1, exitOnError=true)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script.cpp:185
#72 0x0000000000913312 in LuaLoadFile (file="scripts/guichan.lua", strArg="")
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script.cpp:246
#73 0x00000000009857e1 in MenuLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/stratagus.cpp:313
#74 0x00000000009862ae in stratagusMain (argc=1, argv=0x7fffffffdbf8)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/stratagus.cpp:822
#75 0x00000000008deaa0 in main (argc=1, argv=0x7fffffffdbf8)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/main.cpp:37
(gdb) 
```

**Comment by Andrettin** [comment]
Thanks for the report :) Did this happen in a saved game? It looks like a unit was null.

**Comment by KroArtem** [comment]
No, this was a game from scratch.

**Comment by Andrettin** [comment]
It seems like somehow a unit is being deleted while still remaining in the player's unit list. I implemented a check which will avoid a crash, while still giving a message that the unit is null when it shouldn't be:
https://github.com/Andrettin/Wyrmgus/commit/6bcd0cd17946de23f5facd157ced954570cebffc

**Comment by KroArtem** [comment]
I believe this one can be also closed. I didn't have anything similar for a while, otherwise I'll create another ticket.
