### ISSUE TITLE
Segfault after saving and loading a campaign game

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#108]
```
game ends

Thread 1 "stratagus-dbg" received signal SIGSEGV, Segmentation fault.
0x00000000007459a5 in std::max<int> (__a=@0x7fffffffc080: 100, 
    __b=@0x6dec: <error reading variable>)
    at /usr/include/c++/5/bits/stl_algobase.h:224
224	      if (__a < __b)
(gdb) bt
#0  0x00000000007459a5 in std::max<int> (__a=@0x7fffffffc080: 100, 
    __b=@0x6dec: <error reading variable>)
    at /usr/include/c++/5/bits/stl_algobase.h:224
#1  0x0000000000ad0c16 in RemoveUpgradeModifier (player=..., um=0x21884390)
    at /home/kroartem/SVN/Wyrmgus/src/unit/upgrade.cpp:1647
#2  0x0000000000ad2ff5 in UpgradeLost (player=..., id=142)
    at /home/kroartem/SVN/Wyrmgus/src/unit/upgrade.cpp:2057
#3  0x0000000000937302 in CPlayer::SetCivilization (this=0x1a5d760 <Players>, 
    civilization=6) at /home/kroartem/SVN/Wyrmgus/src/stratagus/player.cpp:1354
#4  0x0000000000998941 in CclSetPlayerData (l=0x1c6b010)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script_player.cpp:3184
#5  0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#6  0x00007ffff7bbfeea in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#7  0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#8  0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#9  0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#10 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#11 0x000000000092c6e9 in LuaCallback::run (this=0x230e82b8, results=0)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/luacallback.cpp:149
#12 0x0000000000a3efe8 in LuaActionListener::action (this=0x230e82b0, 
    eventId="") at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:494
#13 0x00000000007e96fc in gcn::Widget::generateAction (this=0x230e80f0)
---Type <return> to continue, or q <return> to quit---
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:616
#14 0x00000000007ecd5d in gcn::Button::mouseClick (this=0x230e80f0, button=1)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/button.cpp:254
#15 0x00000000007e9135 in gcn::Widget::_mouseInputMessage (this=0x230e80f0, 
    mouseInput=...) at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:502
#16 0x00000000007eea31 in gcn::Container::_mouseInputMessage (this=0x2beb3af0, 
    mouseInput=...)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/container.cpp:394
#17 0x00000000007e0aae in gcn::Gui::logic (this=0x1a6d0d20)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/gui.cpp:155
#18 0x0000000000a3ee17 in handleInput (event=0x0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:443
#19 0x0000000000aff158 in WaitEventsOneFrame ()
    at /home/kroartem/SVN/Wyrmgus/src/video/sdl.cpp:977
#20 0x0000000000a4ae07 in MenuScreen::run (this=0x2beb3af0, loop=true)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:3182
#21 0x0000000000b6484c in tolua_stratagus_CMenuScreen_run00 (tolua_S=0x1c6b010)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:27455
#22 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#23 0x00007ffff7bbfeea in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#24 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#25 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#26 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
---Type <return> to continue, or q <return> to quit---
#27 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#28 0x000000000092c6e9 in LuaCallback::run (this=0x22091d18, results=0)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/luacallback.cpp:149
#29 0x0000000000a3efe8 in LuaActionListener::action (this=0x22091d10, 
    eventId="") at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:494
#30 0x00000000007e96fc in gcn::Widget::generateAction (this=0x230d9b40)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:616
#31 0x00000000007ecd5d in gcn::Button::mouseClick (this=0x230d9b40, button=1)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/button.cpp:254
#32 0x00000000007e9135 in gcn::Widget::_mouseInputMessage (this=0x230d9b40, 
    mouseInput=...) at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:502
#33 0x00000000007eea31 in gcn::Container::_mouseInputMessage (this=0x16919550, 
    mouseInput=...)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/container.cpp:394
#34 0x00000000007e0aae in gcn::Gui::logic (this=0x1a6d0d20)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/gui.cpp:155
#35 0x0000000000a3ee17 in handleInput (event=0x0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:443
#36 0x0000000000aff158 in WaitEventsOneFrame ()
    at /home/kroartem/SVN/Wyrmgus/src/video/sdl.cpp:977
#37 0x0000000000a4ae07 in MenuScreen::run (this=0x16919550, loop=true)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:3182
---Type <return> to continue, or q <return> to quit---
#38 0x0000000000b6484c in tolua_stratagus_CMenuScreen_run00 (tolua_S=0x1c6b010)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:27455
#39 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#40 0x00007ffff7bbfe87 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#41 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#42 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#43 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#44 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#45 0x000000000092c6e9 in LuaCallback::run (this=0x220e62a8, results=0)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/luacallback.cpp:149
#46 0x0000000000a3efe8 in LuaActionListener::action (this=0x220e62a0, 
    eventId="") at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:494
#47 0x00000000007e96fc in gcn::Widget::generateAction (this=0x230deac0)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:616
#48 0x00000000007ecd5d in gcn::Button::mouseClick (this=0x230deac0, button=1)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/button.cpp:254
#49 0x00000000007e9135 in gcn::Widget::_mouseInputMessage (this=0x230deac0, 
    mouseInput=...) at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:502
#50 0x00000000007eea31 in gcn::Container::_mouseInputMessage (this=0x221bab20, 
    mouseInput=...)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/container.cpp:394
#51 0x00000000007e0aae in gcn::Gui::logic (this=0x1a6d0d20)
---Type <return> to continue, or q <return> to quit---
    at /home/kroartem/SVN/Wyrmgus/src/guichan/gui.cpp:155
#52 0x0000000000a3ee17 in handleInput (event=0x0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:443
#53 0x0000000000aff158 in WaitEventsOneFrame ()
    at /home/kroartem/SVN/Wyrmgus/src/video/sdl.cpp:977
#54 0x0000000000a4ae07 in MenuScreen::run (this=0x221bab20, loop=true)
    at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:3182
#55 0x0000000000b6484c in tolua_stratagus_CMenuScreen_run00 (tolua_S=0x1c6b010)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:27455
#56 0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#57 0x00007ffff7bbfe87 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#58 0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#59 0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#60 0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#61 0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#62 0x000000000096529b in LuaCall (narg=0, clear=1, exitOnError=true)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script.cpp:185
#63 0x000000000096562c in LuaLoadFile (file="scripts/guichan.lua", strArg="")
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script.cpp:246
#64 0x00000000009dd11f in MenuLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/stratagus.cpp:313
#65 0x00000000009ddbec in stratagusMain (argc=1, argv=0x7fffffffdb68)
---Type <return> to continue, or q <return> to quit---
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/stratagus.cpp:822
#66 0x000000000092ee0c in main (argc=1, argv=0x7fffffffdb68)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/main.cpp:37
(gdb) 
```

**Comment by Andrettin** [comment]
I have committed a potential fix to the issue, let me know if it works:
https://github.com/Andrettin/Wyrmgus/commit/e6bef9a70b5e36c3ea802d070556a764a7c1fc8b

**Comment by KroArtem** [comment]
Works ok, thanks.
