### ISSUE TITLE
Game doesn't mark files as 'in use'

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#109]
Currently it's possible to delete files that are in use, e.g:
I open "Load game" dialog, then manually delete file with savegame and try to load it. Wyrmsun says:
"Can't open file './/wyr/save/game.sav.gz': No such file or directory" but still continues to load resources. After that it crashes:
```
Thread 1 "stratagus-dbg" received signal SIGSEGV, Segmentation fault.
0x00000000007c08c8 in StartMap (filename="~save/game.sav.gz", clean=false)
    at /home/kroartem/SVN/Wyrmgus/src/game/game.cpp:192
192		CurrentMapLayer = ThisPlayer->StartMapLayer;
(gdb) bt
#0  0x00000000007c08c8 in StartMap (filename="~save/game.sav.gz", clean=false)
    at /home/kroartem/SVN/Wyrmgus/src/game/game.cpp:192
#1  0x00000000007d65a3 in StartSavedGame (filename="~save/game.sav.gz")
    at /home/kroartem/SVN/Wyrmgus/src/game/savegame.cpp:216
#2  0x0000000000b1824d in tolua_stratagus_StartSavedGame00 (tolua_S=0x1c6c010)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:1135
#3  0x00007ffff7bb5320 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#4  0x00007ffff7bbfeea in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#5  0x00007ffff7bb577d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#6  0x00007ffff7bb4a5e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#7  0x00007ffff7bb58eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#8  0x00007ffff7bb13a8 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#9  0x00000000009655e5 in LuaCall (narg=0, clear=1, exitOnError=true)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script.cpp:185
#10 0x0000000000965976 in LuaLoadFile (file="scripts/guichan.lua", strArg="")
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script.cpp:246
#11 0x00000000009dd7b9 in MenuLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/stratagus.cpp:313
#12 0x00000000009de286 in stratagusMain (argc=1, argv=0x7fffffffdb68)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/stratagus.cpp:822
#13 0x000000000092ef48 in main (argc=1, argv=0x7fffffffdb68)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/main.cpp:37
(gdb) 

```

Isn't it possible to mark used files so that they won't be possible to delete?

**Comment by Andrettin** [comment]
One thing is that the file wasn't actually being used at the game at the moment; it was accessed when building the list, but wasn't being used while the list was open. It would only be used again when being loaded.

**Comment by KroArtem** [comment]
That's correct, I don't see any workaround for this issue. Probably it's not an issue at all.

**Comment by Andrettin** [comment]
I made it so the load game menu now displays an error message if the player tries to load a file that has been deleted after the list was built:
https://github.com/Andrettin/Wyrmsun/commit/b3c6770c299a297fbbcbadd3ed4ee91db38ef6d2

**Comment by KroArtem** [comment]
Works ok, thanks. Closing this ticket.
