### ISSUE TITLE
Crash when loading a savegame

### ISSUE THREAD

**Issue by AMDmi3** [Andrettin/Wyrmgus#188]
With `wyrm{sun,gus}-5.3.6`, I have a reproducible crash when loading a savegame while a game is running (e.g. it doesn't happen when loading a game from menu right after staring wyrmsun). Trace suggests that the crash happens in unit destruction (which explains why it doesn't happen when loading a game from menu).

```gdb
#0  thr_kill () at thr_kill.S:4
#1  0x0000000803f3bc74 in __raise (s=s@entry=6) at /usr/src/lib/libc/gen/raise.c:52
#2  0x0000000803fed109 in abort () at /usr/src/lib/libc/stdlib/abort.c:67
#3  0x000000000074e2db in __clang_call_terminate ()
#4  0x00000000010acfad in wyrmgus::unit_ref::~unit_ref (this=0x8237386c8)
    at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/unit/unit_ref.cpp:40
#5  0x000000000113bf2b in std::__1::default_delete<wyrmgus::unit_ref>::operator() (this=0x816e76e98, __ptr=0x8237386c8) at /usr/include/c++/v1/__memory/unique_ptr.h:57
#6  0x000000000113c3da in std::__1::__shared_ptr_pointer<wyrmgus::unit_ref*, std::__1::default_delete<wyrmgus::unit_ref>, std::__1::allocator<wyrmgus::unit_ref> >::__on_zero_shared (this=0x816e76e80) at /usr/include/c++/v1/__memory/shared_ptr.h:267
#7  0x0000000000876de1 in std::__1::__shared_count::__release_shared (this=0x816e76e80) at /usr/include/c++/v1/__memory/shared_ptr.h:177
#8  0x0000000000876d89 in std::__1::__shared_weak_count::__release_shared (this=0x816e76e80) at /usr/include/c++/v1/__memory/shared_ptr.h:219
#9  0x000000000093d2dc in std::__1::shared_ptr<wyrmgus::unit_ref>::~shared_ptr (this=0x823733400) at /usr/include/c++/v1/__memory/shared_ptr.h:959
#10 0x0000000001077bee in CUnit::~CUnit (this=0x823733400) at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/unit/unit.cpp:378
#11 0x000000000114ae3b in std::__1::default_delete<CUnit>::operator() (this=0x823692d18, __ptr=0x823733400) at /usr/include/c++/v1/__memory/unique_ptr.h:57
#12 0x000000000114adbc in std::__1::unique_ptr<CUnit, std::__1::default_delete<CUnit> >::reset (this=0x823692d18, __p=0x0) at /usr/include/c++/v1/__memory/unique_ptr.h:318
#13 0x00000000010f9409 in std::__1::unique_ptr<CUnit, std::__1::default_delete<CUnit> >::~unique_ptr (this=0x823692d18) at /usr/include/c++/v1/__memory/unique_ptr.h:272
#14 0x000000000114a395 in std::__1::destroy_at<std::__1::unique_ptr<CUnit, std::__1::default_delete<CUnit> > > (__loc=0x823692d18)
    at /usr/include/c++/v1/__memory/construct_at.h:50
#15 0x000000000114a379 in std::__1::allocator_traits<std::__1::allocator<std::__1::unique_ptr<CUnit, std::__1::default_delete<CUnit> > > >::destroy<std::__1::unique_ptr<CUnit, std::__1::default_delete<CUnit> >, void, void> (__p=0x823692d18) at /usr/include/c++/v1/__memory/allocator_traits.h:317
#16 0x000000000114a338 in std::__1::__vector_base<std::__1::unique_ptr<CUnit, std::__1::default_delete<CUnit> >, std::__1::allocator<std::__1::unique_ptr<CUnit, std::__1::default_delete<CUnit> > > >::__destruct_at_end (this=0x812d3c098, __new_last=0x823691000) at /usr/include/c++/v1/vector:450
#17 0x000000000114a288 in std::__1::__vector_base<std::__1::unique_ptr<CUnit, std::__1::default_delete<CUnit> >, std::__1::allocator<std::__1::unique_ptr<CUnit, std::__1::default_delete<CUnit> > > >::clear (this=0x812d3c098) at /usr/include/c++/v1/vector:374
#18 0x00000000010f9156 in std::__1::vector<std::__1::unique_ptr<CUnit, std::__1::default_delete<CUnit> >, std::__1::allocator<std::__1::unique_ptr<CUnit, std::__1::default_delete<CUnit> > > >::clear (this=0x812d3c098) at /usr/include/c++/v1/vector:796
#19 0x000000000109ebeb in wyrmgus::unit_manager::init (this=0x812d3c080)
    at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/unit/unit_manager.cpp:58
#20 0x00000000010aca1e in wyrmgus::unit_manager::Load (this=0x812d3c080, l=0x805d70a00)
    at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/unit/unit_manager.cpp:236
#21 0x000000000105e80d in CclSlotUsage (l=0x805d70a00) at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/unit/script_unit.cpp:2082
#22 0x00000008020dbcaf in luaD_precall (L=0x805d70a00, func=<optimized out>, func@entry=0x81f7963a0, nresults=0) at ldo.c:320
#23 0x00000008020e9e94 in luaV_execute (L=L@entry=0x805d70a00, nexeccalls=nexeccalls@entry=1) at lvm.c:591
#24 0x00000008020dbf71 in luaD_call (L=0x805d70a00, func=0x81b9fdb60, nResults=0) at ldo.c:378
#25 0x00000008020db2d6 in luaD_rawrunprotected (L=L@entry=0x805d70a00, f=0x8020d6a60 <f_call>, ud=ud@entry=0x7fffffffc810) at ldo.c:116
#26 0x00000008020dc244 in luaD_pcall (L=L@entry=0x805d70a00, func=0x6, u=0x0, u@entry=0x7fffffffc810, old_top=2912, ef=0) at ldo.c:464
#27 0x00000008020d6990 in lua_pcall (L=0x805d70a00, nargs=<optimized out>, nresults=0, errfunc=<optimized out>) at lapi.c:821
#28 0x000000000131bc7a in LuaCall (narg=0, clear=1, exitOnError=true)
    at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/stratagus/script.cpp:183
#29 0x00000000013048c0 in LuaLoadFile (file="/usr/home/marakasov/test.sav.gz", strArg="")
    at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/stratagus/script.cpp:244
#30 0x0000000000a37004 in LoadGame (filepath=...) at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/game/loadgame.cpp:272
#31 0x0000000000a52bda in StartSavedGame (filepath=...) at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/game/savegame.cpp:90
#32 0x0000000000a82d08 in std::experimental::coroutines_v1::coroutine_handle<void>::resume (this=0x81c456370) at /usr/include/c++/v1/experimental/coroutine:121
#33 0x0000000000a82ce5 in boost::asio::detail::awaitable_frame_base<boost::asio::any_io_executor>::resume (this=0x81c456370)
    at /usr/local/include/boost/asio/impl/awaitable.hpp:455
#34 0x0000000000a82b72 in boost::asio::detail::awaitable_thread<boost::asio::any_io_executor>::pump (this=0x7fffffffcd50)
    at /usr/local/include/boost/asio/impl/awaitable.hpp:713
#35 0x0000000000a82a81 in boost::asio::detail::awaitable_handler<boost::asio::any_io_executor>::operator() (this=0x7fffffffcd50)
    at /usr/local/include/boost/asio/impl/use_awaitable.hpp:73
#36 0x0000000000a82a15 in boost::asio::detail::binder0<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor> >::operator() (this=0x7fffffffcd50)
    at /usr/local/include/boost/asio/detail/bind_handler.hpp:60
#37 0x0000000000a83185 in boost::asio::asio_handler_invoke<boost::asio::detail::binder0<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor> > > (function=...)
    at /usr/local/include/boost/asio/handler_invoke_hook.hpp:88
#38 0x0000000000a8315f in boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder0<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor> >, boost::asio::detail::awaitable_handler<boost::asio::any_io_executor> > (function=..., context=...) at /usr/local/include/boost/asio/detail/handler_invoke_helpers.hpp:54
#39 0x0000000000a8310d in boost::asio::detail::asio_handler_invoke<boost::asio::detail::binder0<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor> >, boost::asio::detail::awaitable_handler<boost::asio::any_io_executor> > (function=..., this_handler=0x7fffffffcd50) at /usr/local/include/boost/asio/detail/bind_handler.hpp:111
#40 0x0000000000a8308d in boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder0<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor> >, boost::asio::detail::binder0<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor> > > (function=..., context=...) at /usr/local/include/boost/asio/detail/handler_invoke_helpers.hpp:54
#41 0x0000000000a82f21 in boost::asio::detail::executor_function::complete<boost::asio::detail::binder0<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor> >, std::__1::allocator<void> > (base=0x805d3fbe0, call=true) at /usr/local/include/boost/asio/detail/executor_function.hpp:116
#42 0x0000000000a85172 in boost::asio::detail::executor_function::operator() (this=0x7fffffffce70) at /usr/local/include/boost/asio/detail/executor_function.hpp:64
#43 0x0000000000a85115 in boost::asio::asio_handler_invoke<boost::asio::detail::executor_function> (function=...) at /usr/local/include/boost/asio/handler_invoke_hook.hpp:88
#44 0x0000000000a84d9f in boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::executor_function, boost::asio::detail::executor_function> (function=..., context=...) at /usr/local/include/boost/asio/detail/handler_invoke_helpers.hpp:54
#45 0x0000000000f29ab1 in boost::asio::io_context::basic_executor_type<std::__1::allocator<void>, 0ul>::execute<boost::asio::detail::executor_function> (this=0x7fffffffcfe8, f=...) at /usr/local/include/boost/asio/impl/io_context.hpp:288
#46 0x0000000000f29a21 in boost_asio_execution_execute_fn::impl::operator()<boost::asio::io_context::basic_executor_type<std::__1::allocator<void>, 0ul> const&, boost::asio::detail::executor_function> (this=0x257426 <boost_asio_execution_execute_fn::static_instance<boost_asio_execution_execute_fn::impl>::instance>, t=..., f=...) at /usr/local/include/boost/asio/execution/execute.hpp:208
#47 0x0000000000f2991c in boost::asio::execution::detail::any_executor_base::execute_ex<boost::asio::io_context::basic_executor_type<std::__1::allocator<void>, 0ul> > (ex=..., f=...) at /usr/local/include/boost/asio/execution/any_executor.hpp:894
#48 0x0000000000a8280e in boost::asio::execution::detail::any_executor_base::execute<boost::asio::detail::binder0<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor> > > (this=0x7fffffffcfe8, f=...) at /usr/local/include/boost/asio/execution/any_executor.hpp:611
#49 0x0000000000a825c1 in boost_asio_execution_execute_fn::impl::operator()<boost::asio::any_io_executor, boost::asio::detail::binder0<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor> > > (this=0x257426 <boost_asio_execution_execute_fn::static_instance<boost_asio_execution_execute_fn::impl>::instance>, t=..., f=...) at /usr/local/include/boost/asio/execution/execute.hpp:208
#50 0x0000000000a823e5 in boost::asio::detail::initiate_dispatch::operator()<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor> > (this=0x8198116e9, handler=...) at /usr/local/include/boost/asio/impl/dispatch.hpp:53
#51 0x0000000000a8229d in boost::asio::async_result<boost::asio::use_awaitable_t<boost::asio::any_io_executor>, void ()>::do_init<boost::asio::detail::initiate_dispatch>(boost::asio::detail::awaitable_frame_base<boost::asio::any_io_executor>*, boost::asio::detail::initiate_dispatch&, boost::asio::use_awaitable_t<boost::asio::any_io_executor>) (frame=0x8198116b0, initiation=..., u=...) at /usr/local/include/boost/asio/impl/use_awaitable.hpp:276
#52 0x0000000000a82230 in boost::asio::async_result<boost::asio::use_awaitable_t<boost::asio::any_io_executor>, void ()>::initiate<boost::asio::detail::initiate_dispatch>(boost::asio::detail::initiate_dispatch, boost::asio::use_awaitable_t<boost::asio::any_io_executor>)::{lambda(auto:1*)#1}::operator()<boost::asio::detail::awaitable_frame_base<boost::asio::any_io_executor> >(boost::asio::detail::awaitable_frame_base<boost::asio::any_io_executor>*) const (this=0x8198116d0, frame=0x8198116b0) at /usr/local/include/boost/asio/impl/use_awaitable.hpp:286
#53 0x0000000000a821dd in boost::asio::detail::awaitable_frame_base<boost::asio::any_io_executor>::await_transform<boost::asio::async_result<boost::asio::use_awaitable_t<boost::asio::any_io_executor>, void ()>::initiate<boost::asio::detail::initiate_dispatch>(boost::asio::detail::initiate_dispatch, boost::asio::use_awaitable_t<boost::asio::any_io_executor>)::{lambda(auto:1*)#1}>(boost::asio::async_result<boost::asio::use_awaitable_t<boost::asio::any_io_executor>, void ()>::initiate<boost::asio::detail::initiate_dispatch>(boost::asio::detail::initiate_dispatch, boost::asio::use_awaitable_t<boost::asio::any_io_executor>)::{lambda(auto:1*)#1}, std::__1::enable_if<is_convertible<boost::asio::result_of<boost::asio::async_result<boost::asio::use_awaitable_t<boost::asio::any_io_executor>, void ()>::initiate<boost::asio::detail::initiate_dispatch>(boost::asio::detail::initiate_dispatch, boost::asio::use_awaitable_t<boost::asio::any_io_executor>)::{lambda(auto:1*)#1} (boost::asio::detail::awaitable_frame_base<boost::asio::any_io_executor>*)>::type, boost::asio::detail::awaitable_thread<boost::asio::any_io_executor>*>::value, void>::type*)::result::await_suspend(std::experimental::coroutines_v1::coroutine_handle<void>) (this=0x8198116d0) at /usr/local/include/boost/asio/impl/awaitable.hpp:389
#54 0x0000000000a479b4 in boost::asio::async_result<boost::asio::use_awaitable_t<boost::asio::any_io_executor>, void ()>::initiate<boost::asio::detail::initiate_dispatch>(boost::asio::detail::initiate_dispatch, boost::asio::use_awaitable_t<boost::asio::any_io_executor>) (initiation=..., u=...) at /usr/local/include/boost/asio/impl/use_awaitable.hpp:284
#55 0x0000000000a82d08 in std::experimental::coroutines_v1::coroutine_handle<void>::resume (this=0x8198116b0) at /usr/include/c++/v1/experimental/coroutine:121
#56 0x0000000000a82ce5 in boost::asio::detail::awaitable_frame_base<boost::asio::any_io_executor>::resume (this=0x8198116b0) at /usr/local/include/boost/asio/impl/awaitable.hpp:455
#57 0x0000000000a82b72 in boost::asio::detail::awaitable_thread<boost::asio::any_io_executor>::pump (this=0x7fffffffd310) at /usr/local/include/boost/asio/impl/awaitable.hpp:713
#58 0x0000000000a7e129 in boost::asio::detail::awaitable_thread<boost::asio::any_io_executor>::launch (this=0x7fffffffd310) at /usr/local/include/boost/asio/impl/awaitable.hpp:702
#59 0x00000000014d7f1c in boost::asio::detail::initiate_co_spawn<boost::asio::any_io_executor>::operator()<boost::asio::detail::detached_handler, wyrmgus::event_loop::co_spawn(std::__1::function<boost::asio::awaitable<void, boost::asio::any_io_executor> ()> const&)::$_1>(boost::asio::detail::detached_handler&&, wyrmgus::event_loop::co_spawn(std::__1::function<boost::asio::awaitable<void, boost::asio::any_io_executor> ()> const&)::$_1&&) const (this=0x7fffffffd490, handler=..., f=...) at /usr/local/include/boost/asio/impl/co_spawn.hpp:298
#60 0x00000000014d7d1d in boost::asio::async_result<boost::asio::detached_t, void (std::exception_ptr)>::initiate<boost::asio::detail::initiate_co_spawn<boost::asio::any_io_executor>, boost::asio::detached_t const&, wyrmgus::event_loop::co_spawn(std::__1::function<boost::asio::awaitable<void, boost::asio::any_io_executor> ()> const&)::$_1>(boost::asio::detail::initiate_co_spawn<boost::asio::any_io_executor>&&, boost::asio::detached_t const&, wyrmgus::event_loop::co_spawn(std::__1::function<boost::asio::awaitable<void, boost::asio::any_io_executor> ()> const&)::$_1&&) (initiation=..., args=...) at /usr/local/include/boost/asio/impl/detached.hpp:90
#61 0x00000000014d7cb5 in boost::asio::async_initiate<boost::asio::detached_t const&, void (std::exception_ptr), boost::asio::detail::initiate_co_spawn<boost::asio::any_io_executor>, wyrmgus::event_loop::co_spawn(std::__1::function<boost::asio::awaitable<void, boost::asio::any_io_executor> ()> const&)::$_1>(boost::asio::detail::initiate_co_spawn<boost::asio::any_io_executor>&&, boost::asio::detached_t const&, wyrmgus::event_loop::co_spawn(std::__1::function<boost::asio::awaitable<void, boost::asio::any_io_executor> ()> const&)::$_1&&) (initiation=..., token=..., args=...) at /usr/local/include/boost/asio/async_result.hpp:861
#62 0x00000000014b863a in boost::asio::co_spawn<boost::asio::io_context::basic_executor_type<std::__1::allocator<void>, 0ul>, wyrmgus::event_loop::co_spawn(std::__1::function<boost::asio::awaitable<void, boost::asio::any_io_executor> ()> const&)::$_1, boost::asio::detached_t const&>(boost::asio::io_context::basic_executor_type<std::__1::allocator<void>, 0ul> const&, wyrmgus::event_loop::co_spawn(std::__1::function<boost::asio::awaitable<void, boost::asio::any_io_executor> ()> const&)::$_1&&, boost::asio::detached_t const&, boost::asio::constraint<is_executor<boost::asio::io_context::basic_executor_type<std::__1::allocator<void>, 0ul> >::value||execution::is_executor<boost::asio::io_context::basic_executor_type<std::__1::allocator<void>, 0ul> >::value, int>::type) (ex=..., f=..., token=...) at /usr/local/include/boost/asio/impl/co_spawn.hpp:386
#63 0x00000000014b856a in wyrmgus::event_loop::co_spawn(std::__1::function<boost::asio::awaitable<void, boost::asio::any_io_executor> ()> const&) (this=0x812a000e0, function=...) at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/util/event_loop.cpp:84
#64 0x0000000001307730 in wyrmgus::engine_interface::load_game_deferred (this=0x805d3cc00, filepath=...) at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/stratagus/engine_interface.cpp:704
#65 0x000000000136220c in SingleGameLoop () at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/stratagus/mainloop.cpp:458
#66 0x0000000000a82d08 in std::experimental::coroutines_v1::coroutine_handle<void>::resume (this=0x8300146d0) at /usr/include/c++/v1/experimental/coroutine:121
#67 0x0000000000a82ce5 in boost::asio::detail::awaitable_frame_base<boost::asio::any_io_executor>::resume (this=0x8300146d0) at /usr/local/include/boost/asio/impl/awaitable.hpp:455
#68 0x0000000000a82b72 in boost::asio::detail::awaitable_thread<boost::asio::any_io_executor>::pump (this=0x7fffffffd8b0) at /usr/local/include/boost/asio/impl/awaitable.hpp:713
#69 0x0000000000f3cfc5 in boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code>::operator() (this=0x7fffffffd8b0, ec=...) at /usr/local/include/boost/asio/impl/use_awaitable.hpp:93
#70 0x0000000000f3cf1c in boost::asio::detail::binder1<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code>, boost::system::error_code>::operator() (this=0x7fffffffd8b0) at /usr/local/include/boost/asio/detail/bind_handler.hpp:171
#71 0x0000000000f3cef5 in boost::asio::asio_handler_invoke<boost::asio::detail::binder1<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code>, boost::system::error_code> > (function=...) at /usr/local/include/boost/asio/handler_invoke_hook.hpp:88
#72 0x0000000000f3ce1f in boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder1<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code>, boost::system::error_code>, boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code> > (function=..., context=...) at /usr/local/include/boost/asio/detail/handler_invoke_helpers.hpp:54
#73 0x0000000000f3ccab in boost::asio::detail::handler_work<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code>, boost::asio::any_io_executor, void>::complete<boost::asio::detail::binder1<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code>, boost::system::error_code> > (this=0x7fffffffd8e8, function=..., handler=...) at /usr/local/include/boost/asio/detail/handler_work.hpp:476
#74 0x000000000150af12 in boost::asio::detail::wait_handler<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code>, boost::asio::any_io_executor>::do_complete (owner=0x809b043c0, base=0x830014c00) at /usr/local/include/boost/asio/detail/wait_handler.hpp:76
#75 0x0000000000f23dee in boost::asio::detail::scheduler_operation::complete (this=0x830014c00, owner=0x809b043c0, ec=..., bytes_transferred=0) at /usr/local/include/boost/asio/detail/scheduler_operation.hpp:40
#76 0x0000000001511ed6 in boost::asio::detail::scheduler::do_wait_one (this=0x809b043c0, lock=..., this_thread=..., usec=986, ec=...) at /usr/local/include/boost/asio/detail/impl/scheduler.ipp:573
#77 0x0000000001511810 in boost::asio::detail::scheduler::wait_one (this=0x809b043c0, usec=986, ec=...) at /usr/local/include/boost/asio/detail/impl/scheduler.ipp:249
#78 0x0000000001511587 in boost::asio::io_context::run_one_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > (this=0x809ab1060, abs_time=...) at /usr/local/include/boost/asio/impl/io_context.hpp:98
#79 0x000000000151143d in boost::asio::io_context::run_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > (this=0x809ab1060, abs_time=...) at /usr/local/include/boost/asio/impl/io_context.hpp:73
#80 0x00000000015076bd in boost::asio::io_context::run_for<long long, std::__1::ratio<1l, 1000l> > (this=0x809ab1060, rel_time=...) at /usr/local/include/boost/asio/impl/io_context.hpp:65
#81 0x00000000014b8f21 in wyrmgus::event_loop::run_io_context (this=0x812a000e0) at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/util/event_loop.cpp:107
#82 0x00000000014dea88 in wyrmgus::event_loop::event_loop()::$_2::operator()() const (this=0x805cfca10) at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/util/event_loop.cpp:54
#83 0x00000000014dea37 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, wyrmgus::event_loop::event_loop()::$_2>::call(wyrmgus::event_loop::event_loop()::$_2&, void**) (f=..., arg=0x7fffffffdeb0) at /usr/local/include/qt5/QtCore/qobjectdefs_impl.h:146
#84 0x00000000014dea01 in QtPrivate::Functor<wyrmgus::event_loop::event_loop()::$_2, 0>::call<QtPrivate::List<>, void>(wyrmgus::event_loop::event_loop()::$_2&, void*, void**) (f=..., arg=0x7fffffffdeb0) at /usr/local/include/qt5/QtCore/qobjectdefs_impl.h:256
#85 0x00000000014de9a1 in QtPrivate::QFunctorSlotObject<wyrmgus::event_loop::event_loop()::$_2, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x805cfca00, r=0x805cfc9e0, a=0x7fffffffdeb0, ret=0x0) at /usr/local/include/qt5/QtCore/qobjectdefs_impl.h:443
#86 0x0000000803a6e3df in ?? () from /usr/local/lib/qt5/libQt5Core.so.5
#87 0x0000000803a74553 in QTimer::timerEvent(QTimerEvent*) () from /usr/local/lib/qt5/libQt5Core.so.5
#88 0x0000000803a62a7c in QObject::event(QEvent*) () from /usr/local/lib/qt5/libQt5Core.so.5
#89 0x000000080189c219 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/local/lib/qt5/libQt5Widgets.so.5
#90 0x000000080189d5f8 in QApplication::notify(QObject*, QEvent*) () from /usr/local/lib/qt5/libQt5Widgets.so.5
#91 0x0000000803a39b0f in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/local/lib/qt5/libQt5Core.so.5
#92 0x0000000803a8e758 in QTimerInfoList::activateTimers() () from /usr/local/lib/qt5/libQt5Core.so.5
#93 0x0000000803a902d1 in ?? () from /usr/local/lib/qt5/libQt5Core.so.5
#94 0x0000000804bbb8c2 in g_main_context_dispatch () from /usr/local/lib/libglib-2.0.so.0
#95 0x0000000804bbbc54 in ?? () from /usr/local/lib/libglib-2.0.so.0
#96 0x0000000804bbbd18 in g_main_context_iteration () from /usr/local/lib/libglib-2.0.so.0
#97 0x0000000803a8f840 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/lib/qt5/libQt5Core.so.5
#98 0x0000000803a364e6 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/lib/qt5/libQt5Core.so.5
#99 0x0000000803a3a1be in QCoreApplication::exec() () from /usr/local/lib/qt5/libQt5Core.so.5
#100 0x0000000000752ee0 in main (argc=3, argv=0x7fffffffe810) at /usr/work/usr/home/marakasov/projects/ports/games/wyrmgus/work/Wyrmgus-5.3.6/src/stratagus/main.cpp:194
```

It looks like there's double destruction somewhere, so `CUnit::Release` is called multiple times, the second time throws and since that exception occures in dtor `unit_ref:~unit_ref`, terminate is called. Some more info:

```gdb
(gdb) print ref
$14 = {__ptr_ = 0x8237386c8, __cntrl_ = 0x816e76e80}
(gdb) print base_ref
$15 = {__ptr_ = 0x8237386c8, __cntrl_ = 0x816e76e80}
(gdb) print base_ref->unit
$20 = (CUnit *) 0x823733400
(gdb) print this
$21 = (CUnit *) 0x823733400
(gdb) print base_ref->unit->ReleaseCycle
$16 = 0
(gdb) print *base_ref.__cntrl_
$25 = {<std::__1::__shared_count> = {
    _vptr$__shared_count = 0x1580860 <vtable for std::__1::__shared_ptr_pointer<wyrmgus::unit_ref*, std::__1::default_delete<wyrmgus::unit_ref>, std::__1::allocator<wyrmgus::unit_ref> >+16>, __shared_owners_ = -1}, __shared_weak_owners_ = 0}  # not sure if __shared_owners_ = -1 is legal here
```

**Comment by Andrettin** [comment]
Thank you for letting me know about the bug :) I could reproduce and fix it:
https://github.com/Andrettin/Wyrmgus/commit/260d0ee71b3e8339d159658bb02c2cb1e4ff8def

**Comment by AMDmi3** [comment]
Big thank you for a quick fix! Fix confirmed.
