### ISSUE TITLE
Segfault in HitUnit

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#38]
Ubuntu 15.04 x86_64
Wyrmgus db86a1a00bec2226be74a66710f6256e8d28c912, Wyrmsun 08498a9f3b5a9614ae01190c36365b9ef8769b2e.

I was playing custom game when the crash occured. Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000766f2f in HitUnit (attacker=0x0, target=..., damage=1, missile=
    0x0, show_damage=false)
    at /home/kroartem/SVN/Wyrmgus/src/unit/unit.cpp:3492
3492			if (attacker->Type->BoolFlag[PREDATOR_INDEX].value) { //stop predators so that they can consume the corpse
(gdb) bt
#0  0x0000000000766f2f in HitUnit (attacker=0x0, target=..., damage=1, 
    missile=0x0, show_damage=false)
    at /home/kroartem/SVN/Wyrmgus/src/unit/unit.cpp:3492
#1  0x000000000058d958 in HandleBurnAndPoison (unit=...)
    at /home/kroartem/SVN/Wyrmgus/src/action/actions.cpp:328
#2  0x000000000058da14 in HandleBuffsEachSecond (unit=...)
    at /home/kroartem/SVN/Wyrmgus/src/action/actions.cpp:352
#3  0x000000000058e31e in UnitActionsEachSecond<__gnu_cxx::__normal_iterator<CUnit**, std::vector<CUnit*> > > (begin=, end=)
    at /home/kroartem/SVN/Wyrmgus/src/action/actions.cpp:430
#4  0x000000000058e15e in UnitActions ()
    at /home/kroartem/SVN/Wyrmgus/src/action/actions.cpp:523
#5  0x00000000006b3052 in GameLogicLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:400
#6  0x00000000006b353b in SingleGameLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:562
#7  0x00000000006b35eb in GameMainLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:599
#8  0x00000000005d67c8 in StartMap (filename="~save/autosave.sav.gz", 
    clean=false) at /home/kroartem/SVN/Wyrmgus/src/game/game.cpp:173
#9  0x00000000005e2c32 in StartSavedGame (filename="~save/autosave.sav.gz")
    at /home/kroartem/SVN/Wyrmgus/src/game/savegame.cpp:219
#10 0x00000000007c1dd7 in tolua_stratagus_StartSavedGame00 (tolua_S=0x1a7df80)
---Type <return> to continue, or q <return> to quit---
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:1122
#11 0x00007ffff7bb6220 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#12 0x00007ffff7bc0d8a in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#13 0x00007ffff7bb667d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#14 0x00007ffff7bb595e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#15 0x00007ffff7bb67eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#16 0x00007ffff7bb245c in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#17 0x00000000006be84f in LuaCall (narg=0, clear=1, exitOnError=true)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script.cpp:168
#18 0x00000000006beb8f in LuaLoadFile (file="scripts/guichan.lua")
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/script.cpp:225
#19 0x00000000006e7f26 in MenuLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/stratagus.cpp:305
#20 0x00000000006e88a6 in stratagusMain (argc=1, argv=0x7fffffffdf48)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/stratagus.cpp:787
#21 0x00000000006b1fec in main (argc=1, argv=0x7fffffffdf48)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/main.cpp:37
```

**Comment by Andrettin** [comment]
Thanks for the bug report! This should be fixed in https://github.com/Andrettin/Wyrmgus/commit/e95f81e3e3d7716b2a5f0d086bdf1b8ecee2fcc4
