### ISSUE TITLE
Change upgrade icon logic code

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#61]
There is some defect in code that shows icons for upgraded units, that can lead to crash. Make your hero to level up. An icon will appear. Now let him die. An icon remains. Now after some time the game will crash with the following stacktrace (it's not full, though):

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000007eeac0 in CUnit::GetIcon (this=0xb82e240)
    at /home/kroartem/SVN/Wyrmgus/src/unit/unit.cpp:3784
3784		} else if (Type->VarInfo[Variation] && Type->VarInfo[Variation]->Icon.Icon) {
(gdb) bt
#0  0x00000000007eeac0 in CUnit::GetIcon (this=0xb82e240)
    at /home/kroartem/SVN/Wyrmgus/src/unit/unit.cpp:3784
#1  0x000000000071330d in UpdateDisplay ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:268
#2  0x000000000071424e in DisplayLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:564
#3  0x000000000071426a in SingleGameLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:583
#4  0x000000000071450f in GameMainLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:637
#5  0x0000000000627bd7 in StartMap (filename="maps/nidavellir/aurvang.smp", 
    clean=true) at /home/kroartem/SVN/Wyrmgus/src/game/game.cpp:179
#6  0x00000000008536dc in tolua_stratagus_StartMap00 (tolua_S=0x2925780)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:1067
```

I was trying to debug it and it seemed like Type was null at this point. And hero's icon was changed to usual miner icon. (though when I was pressing it, it was referring to the place where my hero died).

**Comment by Andrettin** [comment]
Thank you! This is fixed now:
https://github.com/Andrettin/Wyrmgus/commit/d8bddee9ba3d474f32e077d4136012021bea7afb
