### ISSUE TITLE
Crash with new Speerkampfer

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#63]
When I tried to create a speerkampfer, a segfault occured.

```
Program received signal SIGSEGV, Segmentation fault.
0x000000000075f3b4 in CIcon::DrawUnitIcon (this=0x0, style=..., flags=32, 
    pos=..., text="", player=0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/icons.cpp:187
187		s.Default.Sprite = s.Hover.Sprite = s.Clicked.Sprite = this->G;
(gdb) bt
#0  0x000000000075f3b4 in CIcon::DrawUnitIcon (this=0x0, style=..., flags=32, 
    pos=..., text="", player=0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/icons.cpp:187
#1  0x0000000000766dba in DrawUnitInfo_Training (unit=...)
    at /home/kroartem/SVN/Wyrmgus/src/ui/mainscr.cpp:481
#2  0x000000000076729d in DrawUnitInfo_single_selection (unit=...)
    at /home/kroartem/SVN/Wyrmgus/src/ui/mainscr.cpp:554
#3  0x0000000000767fbe in DrawUnitInfo (unit=...)
    at /home/kroartem/SVN/Wyrmgus/src/ui/mainscr.cpp:735
#4  0x000000000076a2fd in InfoPanel_draw_single_selection (selUnit=0x0)
    at /home/kroartem/SVN/Wyrmgus/src/ui/mainscr.cpp:1507
#5  0x000000000076aa9d in CInfoPanel::Draw (this=0x1d7a748 <UI+712>)
    at /home/kroartem/SVN/Wyrmgus/src/ui/mainscr.cpp:1571
#6  0x00000000006f3bb6 in UpdateDisplay ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:226
#7  0x00000000006f4f8f in DisplayLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:564
#8  0x00000000006f4fa1 in SingleGameLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:583
#9  0x00000000006f524e in GameMainLoop ()
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/mainloop.cpp:637
#10 0x000000000060c3be in StartMap (filename="maps/earth/prague.smp", 
    clean=true) at /home/kroartem/SVN/Wyrmgus/src/game/game.cpp:179
---Type <return> to continue, or q <return> to quit---
#11 0x000000000083540b in tolua_stratagus_StartMap00 (tolua_S=0x1d90f60)
    at /home/kroartem/SVN/Wyrmgus/tolua.cpp:1067
#12 0x00007ffff7bb6220 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#13 0x00007ffff7bc0d8a in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#14 0x00007ffff7bb667d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#15 0x00007ffff7bb595e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#16 0x00007ffff7bb67eb in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#17 0x00007ffff7bb245c in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#18 0x00000000006efc71 in LuaCallback::run (this=0x93f5328, results=0)
    at /home/kroartem/SVN/Wyrmgus/src/stratagus/luacallback.cpp:149
#19 0x00000000007896d4 in LuaActionListener::action (this=0x93f5320, 
    eventId="") at /home/kroartem/SVN/Wyrmgus/src/ui/widgets.cpp:495
#20 0x0000000000628d1d in gcn::Widget::generateAction (this=0x93f5180)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:616
#21 0x000000000062c059 in gcn::Button::mouseClick (this=0x93f5180, button=1)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/button.cpp:254
#22 0x0000000000628766 in gcn::Widget::_mouseInputMessage (this=0x93f5180, 
    mouseInput=...) at /home/kroartem/SVN/Wyrmgus/src/guichan/widget.cpp:502
#23 0x000000000062dc29 in gcn::Container::_mouseInputMessage (this=0x9397d60, 
    mouseInput=...)
    at /home/kroartem/SVN/Wyrmgus/src/guichan/widgets/container.cpp:394
#24 0x0000000000620721 in gcn::Gui::logic (this=0x8f696d0)
---Type <return> to continue, or q <return> to quit---

```

**Comment by Andrettin** [comment]
Thank you :) I've fixed this now:
https://github.com/Andrettin/Wyrmgus/commit/660dc45a5854225c4dd09e0b3f15684ab64df095
https://github.com/Andrettin/Wyrmsun/commit/5860599cdac5350cb0528881901293e8847fab20
